In [1]:
import numpy as np
import scipy.stats as ss

In [2]:
# calculating probabilities
n=10
p=0.4
r=4

In [3]:
# calculate the binomial probability using binom.pmf
?ss.binom.pmf

Signature: ss.binom.pmf(k, *args, **kwds)
Docstring:
Probability mass function at k of the given RV.

Parameters
----------
k : array_like
    Quantiles.
arg1, arg2, arg3,... : array_like
    The shape parameter(s) for the distribution (see docstring of the
    instance object for more information)
loc : array_like, optional
    Location parameter (default=0).

Returns
-------
pmf : array_like
    Probability mass function evaluated at k
File:      c:\users\deepa\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py
Type:      method

In [4]:
ss.binom.pmf(r,n,p)

0.25082265599999987

In [7]:
# round the values to 3 digits
np.round(ss.binom.pmf(r,n,p),3)

0.251

In [6]:
# Caculating probability for
# P(X<=r)
# Use the binom.cdf function
?ss.binom.cdf

Signature: ss.binom.cdf(k, *args, **kwds)
Docstring:
Cumulative distribution function of the given RV.

Parameters
----------
k : array_like, int
    Quantiles.
arg1, arg2, arg3,... : array_like
    The shape parameter(s) for the distribution (see docstring of the
    instance object for more information).
loc : array_like, optional
    Location parameter (default=0).

Returns
-------
cdf : ndarray
    Cumulative distribution function evaluated at `k`.
File:      c:\users\deepa\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py
Type:      method

In [9]:
np.round(ss.binom.cdf(r,n,p),3)

0.633

In [11]:
# Normal distribution
M=60
sd=10
x=40

In [12]:
#Compute P(X<=x) we will use cdf function

In [13]:
?ss.norm.cdf

Signature: ss.norm.cdf(x, *args, **kwds)
Docstring:
Cumulative distribution function of the given RV.

Parameters
----------
x : array_like
    quantiles
arg1, arg2, arg3,... : array_like
    The shape parameter(s) for the distribution (see docstring of the
    instance object for more information)
loc : array_like, optional
    location parameter (default=0)
scale : array_like, optional
    scale parameter (default=1)

Returns
-------
cdf : ndarray
    Cumulative distribution function evaluated at `x`
File:      c:\users\deepa\anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py
Type:      method

In [14]:
np.round(ss.norm.cdf(x,M,sd),3)

0.023

In [16]:
ss.norm(60,10).cdf(40)

0.022750131948179195

In [18]:
# CAlculate the difference
ss.norm.cdf(80,60,10)-ss.norm.cdf(40,60,10)

0.9544997361036416

In [20]:
#generate randon numbers belonging to a paticular distribution
#Generate 10 random numbers from the binomial distribution with n=10 , p=0.4,size=10(total no of random numbers that you want to geneate
n=10
p=0.4
size=10

In [21]:
np.random.binomial(n,p,size)

array([6, 1, 5, 3, 7, 4, 1, 3, 2, 6])

In [23]:
#generate random numbers for normal distribution
# We will generate total number of 10 numbers
M=60
sd=10

In [24]:
np.random.normal(M,sd,10)

array([57.56332793, 65.28403771, 38.03908923, 75.63616179, 73.39889757,
       75.66136245, 72.54993774, 62.90752577, 71.64538704, 61.04277952])

In [33]:
#Use of seed to generate the same random numbers everytime the code is executed
seed=100
np.random.seed(100)

In [32]:
np.random.normal(M,sd,10)

array([42.50234527, 63.42680403, 71.53035803, 57.47563963, 69.81320787,
       65.14218841, 62.21179669, 49.29956669, 58.10504169, 62.55001444])

In [34]:
np.random.normal(M,sd,10)

array([42.50234527, 63.42680403, 71.53035803, 57.47563963, 69.81320787,
       65.14218841, 62.21179669, 49.29956669, 58.10504169, 62.55001444])

In [35]:
#In order to geneate the same random numbers we need to re-execute the seed first

In [36]:
#Given a list containing nu numbers find the combinations of size r
from itertools import combinations

In [37]:
?combinations

Init signature: combinations(iterable, r)
Docstring:     
Return successive r-length combinations of elements in the iterable.

combinations(range(4), 3) --> (0,1,2), (0,1,3), (0,2,3), (1,2,3)
Type:           type
Subclasses:     

In [38]:
alpha='ABCD'

In [40]:
p=combinations(alpha,3)

In [41]:
p

In [42]:
list(p)

[('A', 'B', 'C'), ('A', 'B', 'D'), ('A', 'C', 'D'), ('B', 'C', 'D')]

In [43]:
beta=['A','B','C','D']

In [44]:
q=combinations(beta,2)

In [45]:
list(q)

[('A', 'B'), ('A', 'C'), ('A', 'D'), ('B', 'C'), ('B', 'D'), ('C', 'D')]

In [46]:
num=[2,3,5,6,7,8]
r=combinations(num,3)
list(r)

[(2, 3, 5),
 (2, 3, 6),
 (2, 3, 7),
 (2, 3, 8),
 (2, 5, 6),
 (2, 5, 7),
 (2, 5, 8),
 (2, 6, 7),
 (2, 6, 8),
 (2, 7, 8),
 (3, 5, 6),
 (3, 5, 7),
 (3, 5, 8),
 (3, 6, 7),
 (3, 6, 8),
 (3, 7, 8),
 (5, 6, 7),
 (5, 6, 8),
 (5, 7, 8),
 (6, 7, 8)]

In [47]:
for c in combinations(num,3):
    if 6 in c:
        print(c)

(2, 3, 6)
(2, 5, 6)
(2, 6, 7)
(2, 6, 8)
(3, 5, 6)
(3, 6, 7)
(3, 6, 8)
(5, 6, 7)
(5, 6, 8)
(6, 7, 8)


In [48]:
for d in combinations(beta,2):
    if 'A' in d:
        print(d)

('A', 'B')
('A', 'C')
('A', 'D')
